name: Build package
# jobs 을 실행할 이벤트를 설정합니다.
on:
  # push 됐을때
  push:
    # 아래 경로에 있는 파일들은 push 가 돼도 job 을 실행하지 않습니다.
    paths-ignore:
      - '.eslintrc.js'
      - '.gitignore'
      - '.prettierrc'
      - '.npmrc'
      - 'README.md'
    # 어떤 branch 에서 동작할 지
    branches:
      - master

# build 를 실행합니다.
jobs:
  publish-github-package-registry:
    # 실행 환경
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 이 부분에서 npmrc 파일을 설정한다고 하는데, 이미 있는 경우 없어도되는걸까요
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@ordinary-yobi'
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
